CREATE TABLE PERSON
  (id INTEGER,
  name NVARCHAR2(500) NOT NULL,
  gender NVARCHAR2(2) NOT NULL,
  trivia CLOB,
  quotes CLOB,
  birthdate DATE,
  deathdate DATE,
  birthname NVARCHAR2(500),
  minibiography CLOB,
  spouse NVARCHAR2(500),
  height FLOAT,
  PRIMARY KEY (id));
    
CREATE TABLE ALTERNATIVE_NAME
  (id INTEGER,
  person_id INTEGER NOT NULL,
  alternative_name NVARCHAR2(500) NOT NULL,
  PRIMARY KEY (id, person_id),
  FOREIGN KEY (person_id) REFERENCES PERSON (id)
    ON DELETE CASCADE);
    
CREATE TABLE PRODUCTION
  (id INTEGER,
  title NVARCHAR2(500) NOT NULL,
  production_year INTEGER,
  series_id INTEGER,
  season_number INTEGER,
  episode_number INTEGER,
  series_year NVARCHAR2(20),
  kind NVARCHAR2(30),
  genre NVARCHAR2(20),
  PRIMARY KEY (id));
  
CREATE TABLE ALTERNATIVE_TITLE
  (id INTEGER,
  production_id INTEGER,
  title NVARCHAR2(1000) NOT NULL,
  PRIMARY KEY (id, production_id),
  FOREIGN KEY (production_id) REFERENCES PRODUCTION (id)
    ON DELETE CASCADE);
    
CREATE TABLE CHARACTER_TABLE
  (id INTEGER,
  name NVARCHAR2(500) NOT NULL,
  PRIMARY KEY (id));
  
CREATE TABLE COMPANY
  (id INTEGER,
  country_code NVARCHAR2(10),
  name NVARCHAR2(200) NOT NULL,
  PRIMARY KEY (id));
  
CREATE TABLE PRODUCTION_COMPANY
  (id INTEGER,
  company_id INTEGER NOT NULL,
  production_id INTEGER NOT NULL,
  company_type NVARCHAR2(50) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (production_id) REFERENCES PRODUCTION (id)
    ON DELETE CASCADE,
  FOREIGN KEY (company_id) REFERENCES COMPANY (id)
    ON DELETE CASCADE);

CREATE TABLE PRODUCTION_CAST
  (id INTEGER,
  production_id INTEGER,
  person_id INTEGER,
  character_id INTEGER,
  role CHAR(30));
  
CREATE TABLE PRODUCTION_CAST
  (id INTEGER,
  production_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  character_id INTEGER,
  role CHAR(30) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (production_id) REFERENCES PRODUCTION (id)
    ON DELETE CASCADE,
  FOREIGN KEY (person_id) REFERENCES PERSON (id)
    ON DELETE CASCADE,
  FOREIGN KEY (character_id) REFERENCES CHARACTER_TABLE (id)
    ON DELETE CASCADE);
  
DROP TABLE PRODUCTION_CAST;
DROP TABLE PRODUCTION_COMPANY;
DROP TABLE COMPANY;
DROP TABLE CHARACTER_TABLE;
DROP TABLE ALTERNATIVE_TITLE;
DROP TABLE PRODUCTION;
DROP TABLE ALTERNATIVE_NAME;
DROP TABLE PERSON;